ConfigurationMessage:
  persistent_archive: 
    resource_reference: 
      key: ""
      type: 
        object_id: -1
        version: -1
      isleaf: true
    configuration: 
      key: ""
      type: 
        object_id: -1
        version: -1
      isleaf: true
    life_cycle_operation: ACTIVATE
  cache: 
    resource_reference: 
      key: ""
      type: 
        object_id: -1
        version: -1
      isleaf: true
    configuration: 
      key: ""
      type: 
        object_id: -1
        version: -1
      isleaf: true
    life_cycle_operation: ACTIVATE