ResourceConfigurationResponse:
  resource_reference: 
    key: ""
    type: 
      object_id: -1
      version: -1
    isleaf: true
  configuration: 
    key: ""
    type: 
      object_id: -1
      version: -1
    isleaf: true
  result: ""