# Configuration file for setting log levels.
# The contents are transformed into a dict that
# supports dot notation. Example entry:
#
# anode:
#   datastore:
#     couchdb_datastore:
#       CouchDB_DataStore: debug

anode:
  datastore:
    couchdb_datastore:
      CouchDB_DataStore: debug