# Central configuration file for defining the list of services
# to start in the capability container.
# The contents are transformed into a dict that supports dot notation:

datastore:
  name: datastore
  class: prototype.datastore_service.DataStoreService

bank:
  name: bank
  class: prototype.bank.BankService