# _ID = 9001
# _VERSION = 1
obj:
  ApplicationIntegrationServiceRequestMsg:
    message_parameters_reference: 
      key: ""
      type: 
        object_id: -1
        version: -1
      isleaf: true
--- # _ID = 9001