# _ID = 10
# _VERSION = 1
obj:
  ResourceConfigurationRequest:
    resource_reference: 
      key: ""
      type: 
        object_id: -1
        version: -1
      isleaf: true
    configuration: 
      key: ""
      type: 
        object_id: -1
        version: -1
      isleaf: true
    life_cycle_operation: ACTIVATE
--- # _ID = 10